
import React from 'react';
import { RecipeData } from '@/types/recipeTypes';
import RecipeDisplay from '@/components/recipe/RecipeDisplay';
import { Button } from '@/components/ui/button';
import { AlertCircle } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

interface AIRecipeDisplayProps {
  recipe: RecipeData;
  onEdit?: () => void;
  onSave?: () => void;
  onClose?: () => void;
}

const AIRecipeDisplay: React.FC<AIRecipeDisplayProps> = ({ 
  recipe, 
  onEdit, 
  onSave,
  onClose
}) => {
  if (!recipe) {
    return null;
  }

  return (
    <div className="space-y-4">
      <Alert>
        <AlertCircle className="h-4 w-4" />
        <AlertTitle>AI Generated Recipe</AlertTitle>
        <AlertDescription>
          This recipe was generated by AI. Feel free to edit it before saving.
        </AlertDescription>
      </Alert>

      <div className="flex justify-between items-center mb-4">
        <h2 className="text-2xl font-serif">Generated Recipe</h2>
        {onClose && (
          <Button variant="outline" size="sm" onClick={onClose}>
            Close
          </Button>
        )}
      </div>

      <RecipeDisplay
        recipe={recipe}
        onEdit={onEdit}
        onSave={onSave}
      />
    </div>
  );
};

export default AIRecipeDisplay;
